# encoding=utf8
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

desks = [
{ "nickName" : "자바지기" , "imgName" :"1.1.JPG", "name": "서동규" },
{ "nickName" : "씨지기" , "imgName" :"1.2.JPG", "name": "이진우" },
{ "nickName" : "브라운정령" , "imgName" :"1.3.JPG", "name": "정다영글"},
{ "nickName" : "깃지기" , "imgName" :"1.4.JPG", "name": "정희수" },
{ "nickName" : "영어지기" , "imgName" :"2.1.JPG", "name": "고예슬" },
{ "nickName" : "머신러닝지기" , "imgName" :"2.2.JPG", "name": "고형진" },
{ "nickName" : "수학지기" , "imgName" :"2.3.JPG", "name": "김다혜" },
{ "nickName" : "논리지기" , "imgName" :"2.4.JPG", "name": "김연우" },
{ "nickName" : "탁구정령" , "imgName" :"2.5.jpg", "name": "김정봉" },
{ "nickName" : "자구알고수" , "imgName" :"2.6.JPG", "name": "남현욱" },
{ "nickName" : "바나나정령" , "imgName" :"2.7.JPG", "name": "류우림" },
{ "nickName" : "지니어스지기" , "imgName" :"2.8.JPG", "name": "박성호" },
{ "nickName" : "일러지기" , "imgName" :"2.9.JPG", "name": "박신영" },
{ "nickName" : "3마을정령" , "imgName" :"2.10.JPG", "name": "박태준" },
{ "nickName" : "목소리큼정령" , "imgName" :"2.11.JPG", "name": "배철오" },
{ "nickName" : "행복정령" , "imgName" :"2.12.jpg", "name": "선승현" },
{ "nickName" : "도서지기" , "imgName" :"2.13.jpg", "name": "송원석" },
{ "nickName" : "2마을정령" , "imgName" :"2.14.JPG", "name": "심보희" },
{ "nickName" : "짤정령" , "imgName" :"2.15.JPG", "name": "우재우" },
{ "nickName" : "노드지기" , "imgName" :"2.16.JPG", "name": "이경륜" },
{ "nickName" : "새침정령" , "imgName" :"2.17.JPG", "name": "이규원" },
{ "nickName" : "진저지기" , "imgName" :"2.18.JPG", "name": "이재봉" },
{ "nickName" : "귀요미정령" , "imgName" :"2.19.JPG", "name": "임예림" },
{ "nickName" : "웃음정령" , "imgName" :"1.5.JPG", "name": "임정민" },
{ "nickName" : "핫도그정령" , "imgName" :"2.20.JPG", "name": "정원철" },
{ "nickName" : "통계지기" , "imgName" :"2.21.JPG", "name": "조부용" },
{ "nickName" : "디발자지기" , "imgName" :"1.6.JPG", "name": "진유림" },
{ "nickName" : "그래픽스지기" , "imgName" :"2.22.JPG", "name": "최승희" },
{ "nickName" : "프렌즈팝고수" , "imgName" :"1.7.JPG", "name": "하채영" },
{ "nickName" : "다운자바지기" , "imgName" :"2.23.jpg", "name": "하태호" },
{ "nickName" : "철학정령" , "imgName" :"1.8.jpg", "name": "황정민" },
{ "nickName" : "드론지기" , "imgName" :"3.1.JPG", "name": "류성현" },
{ "nickName" : "토이정령" , "imgName" :"3.2.JPG", "name": "박송희" },
{ "nickName" : "콜라정령" , "imgName" :"3.3.JPG", "name": "박용민" },
{ "nickName" : "버거킹정령" , "imgName" :"3.4.jpg", "name": "이성천" },
{ "nickName" : "자구알고수" , "imgName" :"0.1.JPG" , "name":"김동진" },
{ "nickName" : "애플정령" , "imgName" :"0.2.JPG", "name": "김정" },
{ "nickName" : "초고수" , "imgName" : "0.3.jpg", "name":"김종규" },
{ "nickName" : "프런트앤드고수" , "imgName" :"0.4.JPG" , "name":"김태곤" },
{ "nickName" : "슈퍼자바지기" , "imgName" :"0.5.JPG" , "name":"박재성" },
{ "nickName" : "시스템고수" , "imgName" : "0.6.JPG", "name":"배영현" },
{ "nickName" : "인터렉션고수" , "imgName" : "0.7.JPG", "name":"서경진" },
{ "nickName" : "엑셀고수" , "imgName" : "0.8.JPG", "name":"이남영" },
{ "nickName" : "디비고수" , "imgName" : "0.9.JPG", "name":"이익훈" },
{ "nickName" : "맞아?정령" , "imgName" : "0.10.JPG", "name":"임석현" },
{ "nickName" : "프런트앤드지기" , "imgName" :"0.11.jpg" , "name":"전용우" },
{ "nickName" : "경영고수" , "imgName" : "0.12.JPG", "name":"주형철" }
]