# encoding=utf8
import sys
reload(sys)
sys.setdefaultencoding('utf-8')

desks = [
{ "nickName" : "자바지기" , "imgName" : "1기_서동규.JPG" },
{ "nickName" : "씨지기" , "imgName" : "1기_이진우.JPG" },
{ "nickName" : "브라운정령" , "imgName" : "1기_정다영글.JPG"},
{ "nickName" : "깃지기" , "imgName" : "1기_정희수.JPG" },
{ "nickName" : "영어지기" , "imgName" : "2기_고예슬.JPG" },
{ "nickName" : "머신러닝지기" , "imgName" : "2기_고형진.JPG" },
{ "nickName" : "수학지기" , "imgName" : "2기_김다혜.JPG" },
{ "nickName" : "논리지기" , "imgName" : "2기_김연우.JPG" },
{ "nickName" : "탁구정령" , "imgName" : "2기_김정봉.jpg" },
{ "nickName" : "자구알고수" , "imgName" : "2기_남현욱.JPG" },
{ "nickName" : "바나나정령" , "imgName" : "2기_류우림.JPG" },
{ "nickName" : "지니어스지기" , "imgName" : "2기_박성호.JPG" },
{ "nickName" : "일러지기" , "imgName" : "2기_박신영.JPG" },
{ "nickName" : "3마을정령" , "imgName" : "2기_박태준.JPG" },
{ "nickName" : "목소리큼정령" , "imgName" : "2기_배철오.JPG" },
{ "nickName" : "행복정령" , "imgName" : "2기_선승현.jpg" },
{ "nickName" : "도서지기" , "imgName" : "2기_송원석.jpg" },
{ "nickName" : "2마을정령" , "imgName" : "2기_심보희.JPG" },
{ "nickName" : "짤정령" , "imgName" : "2기_우재우.JPG" },
{ "nickName" : "노드지기" , "imgName" : "2기_이경륜.JPG" },
{ "nickName" : "새침정령" , "imgName" : "2기_이규원.JPG" },
{ "nickName" : "진저지기" , "imgName" : "2기_이재봉.JPG" },
{ "nickName" : "귀요미정령" , "imgName" : "2기_임예림.JPG" },
{ "nickName" : "웃음정령" , "imgName" : "2기_임정민.JPG" },
{ "nickName" : "핫도그정령" , "imgName" : "2기_정원철.JPG" },
{ "nickName" : "통계지기" , "imgName" : "2기_조부용.JPG" },
{ "nickName" : "디발자지기" , "imgName" : "2기_진유림.JPG" },
{ "nickName" : "그래픽스지기" , "imgName" : "2기_최승희.JPG" },
{ "nickName" : "프렌즈팝고수" , "imgName" : "2기_하채영.JPG" },
{ "nickName" : "다운자바지기" , "imgName" : "2기_하태호.jpg" },
{ "nickName" : "철학정령" , "imgName" : "2기_황정민.jpg" },
{ "nickName" : "드론지기" , "imgName" : "3기_류성현.JPG" },
{ "nickName" : "토이정령" , "imgName" : "3기_박송희.JPG" },
{ "nickName" : "콜라정령" , "imgName" : "3기_박용민.JPG" },
{ "nickName" : "버거킹정령" , "imgName" : "3기_이성천.jpg" },
{ "nickName" : "자구알고수" , "imgName" : "교수님_김동진.JPG" },
{ "nickName" : "애플정령" , "imgName" : "교수님_김정.JPG" },
{ "nickName" : "초고수" , "imgName" : "교수님_김종규.jpg" },
{ "nickName" : "프런트앤드고수" , "imgName" : "교수님_김태곤.JPG" },
{ "nickName" : "슈퍼자바지기" , "imgName" : "교수님_박재성.JPG" },
{ "nickName" : "시스템고수" , "imgName" : "교수님_배영현.JPG" },
{ "nickName" : "인터렉션고수" , "imgName" : "교수님_서경진.JPG" },
{ "nickName" : "엑셀고수" , "imgName" : "교수님_이남영.JPG" },
{ "nickName" : "디비고수" , "imgName" : "교수님_이익훈.JPG" },
{ "nickName" : "맞아?정령" , "imgName" : "교수님_임석현.JPG" },
{ "nickName" : "프런트앤드지기" , "imgName" : "교수님_전용우.jpg" },
{ "nickName" : "경영고수" , "imgName" : "교수님_주형철.JPG" }
]